name: OSMQuests
version: 1.0.0
description: OSM Quests
author: sho
main: dev.shog.osm.quest.OsmQuests
commands:
  xp:
    description: View your XP.
  quests:
    description: View your complete and uncomplete quests.